/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonExample {
        "loading": boolean;
        "name": string;
    }
    interface ExampleButton {
        "loading": boolean;
        "name": string;
        "variant": string;
    }
    interface FormInput {
        "placeholder": string;
        "type": string;
    }
    interface FormLabel {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyDashboard {
        "image": string;
    }
    interface MyLogo {
        "image": string;
    }
    interface TailwindComponent {
    }
    interface TodoList {
        "name": string;
    }
    interface TodoListItem {
        "thingToDo": string;
    }
}
declare global {
    interface HTMLButtonExampleElement extends Components.ButtonExample, HTMLStencilElement {
    }
    var HTMLButtonExampleElement: {
        prototype: HTMLButtonExampleElement;
        new (): HTMLButtonExampleElement;
    };
    interface HTMLExampleButtonElement extends Components.ExampleButton, HTMLStencilElement {
    }
    var HTMLExampleButtonElement: {
        prototype: HTMLExampleButtonElement;
        new (): HTMLExampleButtonElement;
    };
    interface HTMLFormInputElement extends Components.FormInput, HTMLStencilElement {
    }
    var HTMLFormInputElement: {
        prototype: HTMLFormInputElement;
        new (): HTMLFormInputElement;
    };
    interface HTMLFormLabelElement extends Components.FormLabel, HTMLStencilElement {
    }
    var HTMLFormLabelElement: {
        prototype: HTMLFormLabelElement;
        new (): HTMLFormLabelElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyDashboardElement extends Components.MyDashboard, HTMLStencilElement {
    }
    var HTMLMyDashboardElement: {
        prototype: HTMLMyDashboardElement;
        new (): HTMLMyDashboardElement;
    };
    interface HTMLMyLogoElement extends Components.MyLogo, HTMLStencilElement {
    }
    var HTMLMyLogoElement: {
        prototype: HTMLMyLogoElement;
        new (): HTMLMyLogoElement;
    };
    interface HTMLTailwindComponentElement extends Components.TailwindComponent, HTMLStencilElement {
    }
    var HTMLTailwindComponentElement: {
        prototype: HTMLTailwindComponentElement;
        new (): HTMLTailwindComponentElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLTodoListItemElement extends Components.TodoListItem, HTMLStencilElement {
    }
    var HTMLTodoListItemElement: {
        prototype: HTMLTodoListItemElement;
        new (): HTMLTodoListItemElement;
    };
    interface HTMLElementTagNameMap {
        "button-example": HTMLButtonExampleElement;
        "example-button": HTMLExampleButtonElement;
        "form-input": HTMLFormInputElement;
        "form-label": HTMLFormLabelElement;
        "my-component": HTMLMyComponentElement;
        "my-dashboard": HTMLMyDashboardElement;
        "my-logo": HTMLMyLogoElement;
        "tailwind-component": HTMLTailwindComponentElement;
        "todo-list": HTMLTodoListElement;
        "todo-list-item": HTMLTodoListItemElement;
    }
}
declare namespace LocalJSX {
    interface ButtonExample {
        "loading"?: boolean;
        "name"?: string;
    }
    interface ExampleButton {
        "loading"?: boolean;
        "name"?: string;
        "variant"?: string;
    }
    interface FormInput {
        "placeholder"?: string;
        "type"?: string;
    }
    interface FormLabel {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyDashboard {
        "image"?: string;
    }
    interface MyLogo {
        "image"?: string;
    }
    interface TailwindComponent {
    }
    interface TodoList {
        "name"?: string;
    }
    interface TodoListItem {
        "thingToDo"?: string;
    }
    interface IntrinsicElements {
        "button-example": ButtonExample;
        "example-button": ExampleButton;
        "form-input": FormInput;
        "form-label": FormLabel;
        "my-component": MyComponent;
        "my-dashboard": MyDashboard;
        "my-logo": MyLogo;
        "tailwind-component": TailwindComponent;
        "todo-list": TodoList;
        "todo-list-item": TodoListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-example": LocalJSX.ButtonExample & JSXBase.HTMLAttributes<HTMLButtonExampleElement>;
            "example-button": LocalJSX.ExampleButton & JSXBase.HTMLAttributes<HTMLExampleButtonElement>;
            "form-input": LocalJSX.FormInput & JSXBase.HTMLAttributes<HTMLFormInputElement>;
            "form-label": LocalJSX.FormLabel & JSXBase.HTMLAttributes<HTMLFormLabelElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-dashboard": LocalJSX.MyDashboard & JSXBase.HTMLAttributes<HTMLMyDashboardElement>;
            "my-logo": LocalJSX.MyLogo & JSXBase.HTMLAttributes<HTMLMyLogoElement>;
            "tailwind-component": LocalJSX.TailwindComponent & JSXBase.HTMLAttributes<HTMLTailwindComponentElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
            "todo-list-item": LocalJSX.TodoListItem & JSXBase.HTMLAttributes<HTMLTodoListItemElement>;
        }
    }
}
